# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: \.ipynb$
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/iterative/dvc
    rev: 3.67.1
    hooks:
      - id: dvc-pre-commit
        language_version: python3
      - id: dvc-pre-push
        language_version: python3
