stages:
  process_features:
    cmd: uv run python pipelines/process_features.py
    deps:
      - fof8-gen/data/raw
      - pipelines/process_features.py
      - pipelines/conf/data/
      - pipelines/conf/transform.yaml
    outs:
      - fof8-ml/data/processed/features.parquet

  train_classifier:
    cmd: uv run python pipelines/train_classifier.py
    deps:
      - fof8-ml/data/processed/features.parquet
      - pipelines/train_classifier.py
      - pipelines/conf/classifier_pipeline.yaml
      - pipelines/conf/
    outs:
      - outputs/classifier_metrics.json

  train_regressor:
    cmd: uv run python pipelines/train_regressor.py
    deps:
      - fof8-ml/data/processed/features.parquet
      - pipelines/train_regressor.py
      - pipelines/conf/regressor_pipeline.yaml
      - pipelines/conf/
    outs:
      - outputs/regressor_metrics.json
