name: "catboost_survival"
params:
  iterations: 3000
  learning_rate: 0.039367160674253554
  depth: 6
  loss_function: "Logloss"
  eval_metric: "Logloss"
  early_stopping_rounds: 50
  l2_leaf_reg: 3.540330346531539
  random_strength: 1.548335194171545
  auto_class_weights: "Balanced"
  colsample_bylevel: 1.0
  one_hot_max_size: 2
  min_data_in_leaf: 27
  bagging_temperature: 4.330880728874676